### ISSUE TITLE
Submit the plugin to Packagist

### ISSUE THREAD

**Issue by juho-jaakkola** [manacim/Landr#2]
Now that the plugins has a `composer.json` file, it can be submitted to Packagist: https://packagist.org/packages/submit

Thanks to this, it will be possible to install the plugin with Composer without the need to explicitly define an installation source (such as e.g. these: https://github.com/sbwtech/sbw/blob/6a6c8c45d5bda0330356fd880d235576d80b39e1/composer.json#L7-L16)

**Comment by demyxco** [comment]
https://packagist.org/packages/demyx/landr
