### ISSUE TITLE
Tag the releases

### ISSUE THREAD

**Issue by juho-jaakkola** [manacim/Landr#6]
Each release should have it's own git tag (that ideally uses http://semver.org/).

This way it is possible to install a specific release by giving the git tag (e.g. "1.4.0") as a parameter to Composer.

**Comment by demyxco** [comment]
I will be doing that from now on starting from 1.x.x and up.

**Comment by juho-jaakkola** [comment]
I do not see any releases yet: https://github.com/manacim/Landr/releases

You can tag the [current release](https://github.com/manacim/Landr/blob/master/manifest.xml#L6) from command line with:
```
git tag -a 2.0.0
git push origin 2.0.0
```

**Comment by demyxco** [comment]
I haven't made any new releases yet. I'm waiting for 2.3 to be stable.

**Comment by juho-jaakkola** [comment]
Is there a reason not to start tagging with the current version?

**Comment by demyxco** [comment]
I just finished with the tagging. I also uploaded a new repo for my Instagram plugin.
