### ISSUE TITLE
Potential redirect bug in Elgg 2.3.0

### ISSUE THREAD

**Issue by juho-jaakkola** [manacim/Landr#7]
I tried the plugin in Elgg `2.3.0-rc.1` and I noticed that after logging in, the user gets forwarded to the landing page instead of the activity page.

**Comment by demyxco** [comment]
Ok, let me check what's going on here.

**Comment by juho-jaakkola** [comment]
Apparently this part is not working for some reason: https://github.com/manacim/Landr/blob/master/views/default/page/layouts/landr.php#L16-L18

BTW, it would be better to do that check already in the `landr()` function declared in `start.php`:

``` php
function landr() {
        if (elgg_is_logged_in()) {
                forward('activity');
        } else {
                echo elgg_view_page('', elgg_view_layout('landr'));
        }
}
```

**Comment by demyxco** [comment]
I'm not getting the redirect bug that you're getting. I freshly installed the 2.3 RC-1 on my office web server and I'm not getting any errors or redirections both on computer and mobile. You can check it out at:

URL: http://cims.ddns.net
User: demo
Password: master

**Comment by demyxco** [comment]
I just noticed the server was down, did you check it?

**Comment by ghost** [comment]
I do get the missing redirect to activity page when logging in to your demo site. When logging in the user stays in homepage (like still being logged out).
Sorry :)

**Comment by demyxco** [comment]
@michelesbw try @juho-jaakkola's solution up top and see where that goes.
